singer-io/tap-google-analytics

- .github/pull_request_template.md
- setup.py
- spikes/discover_metrics_and_dimensions.py
- spikes/listing_custom_metrics_and_dimensions.py
- tap_google_analytics/__init__.py
Merging Dev in to resolve conflicts with robot Chris.
- N/A all spikes, just getting circle in an acceptable state.
- None
> WIP Spiking Branch - Conflict Resolution Merge

- tap_google_analytics/client.py
- tap_google_analytics/sync.py
This PR improves the logging in the tap by logging which `tap_stream_id` + `view_id` is currently being synced as well as using the Singer helpers to log http request time metrics and record counter metrics on a per stream basis.
- Pulled data and confirmed that logs are correct.
- None
> Improve logging

- CHANGELOG.md
- setup.py
Bump version to 0.2.0
- Low
- bump version again, rollback #11 and re-release
> bump version; add changelog

- CHANGELOG.md
- setup.py
Version bump for exception handling in #14 
- N/A
- Low, it's a version bump
> Version 0.2.1 and changelog

- CHANGELOG.md
- setup.py
Version bump to 0.3.0 for #16 
- N/A
- Low, version bump PR
- revert #16, bump patch version, and release
> Version 0.3.0 and changelog

- CHANGELOG.md
- setup.py
Bump version for PR #18 
- N/A
- Low, it's a version bump, the risk is in #18 
- revert #18 and bump patch version.
> Version 0.4.0 and changelog

- CHANGELOG.md
- setup.py
Version bump for #20
- N/A 
- Low, just a version and changelog
- revert #20, bump patch version again and re-release
> Version 0.4.1 and changelog

- CHANGELOG.md
- setup.py
Updating patch version for #22
- N/A
- Low, it's a version bump, risks captured in #22 
- revert #22, bump patch version, and re-release
> Version 0.4.2 and changelog

- CHANGELOG.md
- setup.py
Version bump and changelog for #24 
- N/A
- Low, risks accounted for in #24
- revert #24, bump patch version, and re-release
> Version 0.4.3 and changelog

- CHANGELOG.md
- setup.py
Version bump and changelog entry for #26
- N/A
- Low, risks accounted for in #26 
- revert #26, bump patch version, redeploy
> Version 0.4.4 and changelog

- tap_google_analytics/client.py
Raise exception with error message details  - see support ticket https://stitchdata.atlassian.net/browse/SUP-1606
- 
> All 4xx errors that are not retryable should show error message

- CHANGELOG.md
- setup.py
Releasing error message improvement for 4xx non-retryable errors. See support ticket https://stitchdata.atlassian.net/browse/SUP-1606
- 
> Increment version number from 0.4.4 to 0.4.5

- CHANGELOG.md
- setup.py
Version bump and changelog for #32 release
- N/A
- Low, accounted for in #32
- revert #32 and release new patch version
> Version 0.4.7 and changelog

- tap_google_analytics/__init__.py
- tap_google_analytics/client.py
Cache profile lookup so we can reduce the usage of our GA quota.
- 
> Cache profile lookup

- CHANGELOG.md
- setup.py
(write a short description here or paste a link to JIRA)
- 
> Bump version to 0.5.1

- CHANGELOG.md
- setup.py
https://stitchdata.atlassian.net/browse/SUP-2052
- 
> Bump version to 1.0.1 and update changelog

- CHANGELOG.md
- setup.py
> bumped version to 1.0.3

- .circleci/config.yml
Move tests-pylint step to after the integration tests step.
Remove when: always from integration tests step.
Update disable list for tests-pylint.
- 
> add 'use-a-generator' to disables list

- setup.py
- tap_google_analytics/client.py
- tests/test_google_analytics_bookmarks.py
pylint failed because there was a new version of pylint with new rules.  To make sure we don't fail based on a new pylint version we should pin the version and update to the latest intentionally.
https://app.circleci.com/pipelines/github/singer-io/tap-google-analytics/775/workflows/b792f266-2a32-4d6c-ba11-1659cefef537/jobs/801
- 
> Pin pylint and fix pylint issues

- CHANGELOG.md
- setup.py
Request Timeout Implementation
- 
> Bump to version 1.1.1

- .circleci/config.yml
Remove the pip/setuptools upgrade from the build.
- 
> unpin setuptools and pip

- tap_google_analytics/client.py
- tests/unittests/test_client_utilities.py
- Added the error handling for error codes mentioned in the [doc link1](https://developers.google.com/analytics/devguides/reporting/core/v4/errors) and [doc link2](https://developers.google.com/analytics/devguides/config/mgmt/v3/errors)
- Added unit tests to ensure that the code works expectedly,
- For the corresponding error codes, the tap should throw errors with appropriate messages.
- 
> TDL-17695 Add custom error handling

- tap_google_analytics/client.py
- tests/base.py
- tests/test_google_analytics_automatic_fields.py
- tests/test_google_analytics_bookmarks.py
- tests/test_google_analytics_discovery.py
- tests/test_google_analytics_dynamic_dimension_metric.py
- tests/unittests/test_client_utilities.py
> Crest master

- CHANGELOG.md
- setup.py
1) Custom Error handling
2) Missing Test Cases
- 
> Minor version bump

- .circleci/config.yml
- tests/base.py
- tests/test_google_analytics_dynamic_dimension_metric.py
- tests/test_google_analytics_start_date.py
Save test logs as artifacts, use tap-tester logger.
- 
> save test logs

- tests/test_google_analytics_start_date.py
Stabilize start date test by adjusting start dates for sync jobs.  It is believed that the rare failures of this test are due to new records coming in after the first sync but before the second sync such that the second sync has unique records that are not captured in the first sync.  The test assumes no new data and asserts that the second sync records are a subset of the first sync records.  This update swaps start dates for the sync so that the test uses the newer start date for the first sync and the older start date for the second sync.  Now if new records come in for the second sync it does not break the assertion.
- 
> Stabilize start date test by adjusting start dates for sync jobs

- tests/test_google_analytics_bookmarks.py
- tests/test_google_analytics_start_date.py
Stabilize start-date and bookmarks for 'Acquisition Overview' stream
- 
> Stabilize start-date and bookmarks for 'Acquisition Overview' stream

- tests/base.py
- tests/test_google_analytics_bookmarks.py
Update tests for static data
- 
> Update tests for static data
