singer-io/tap-google-analytics

tap_google_analytics/__init__.py
`end_date` from the config file provided was not being parsed into a `datetime` object leading to an exception later in the code.
- Pulled data with an `end_date`
- None
=> Parse end_date string from config

setup.py, tap_google_analytics/__init__.py, tap_google_analytics/client.py
Enables the possibility of using a Service Account to connect to the API
- Did a 'discovery' with both OAuth2 and Service Account credentials
-  None
=> Add support for service account authentication

tap_google_analytics/__init__.py
It appears that we missed the singer standard of logging top-level exceptions as `CRITICAL` in order to parse out the final error mesage successfully.
This PR adds that so it gets wrapped into 1.0.0.
- Ran a local test connection and confirmed that it logged `CRITICAL`
- Low, this is additive and logging-related
=> Log top level exceptions as critical

tap_google_analytics/reports.py, tests/test_google_analytics_basic_sync.py
It seems that searchKeyword isn't something that's collected by default, nor shown on the overview report's dashboard by default, so this PR removes it from the `Behavior Overview` pre-made report definition's default dimensions.
- None, this should be covered by automation
- Low, this is removal of a default, it won't affect any catalogs with the field already selected.
=> Remove searchkeyword from behavior overview defaults

tap_google_analytics/discover.py, tap_google_analytics/sync.py
Correct the datetime parsing behavior for fields in the `Time` group. These come back using non-ISO types, so they were being rejected by the Transformer.
This adds a step before writing the records that will parse them as datetimes and convert them to ISO-8601 format (at UTC timezone).
- Ran through a manual sync and inspected the values at each conversion step.
- Medium, I'm adding a new field to the datetime types mapping, which could result in mixed datatypes for some users.
- revert this branch, bump patch version and re-release
=> Parse datetimes using Google's format

tap_google_analytics/client.py
It appears that google is inconsistent about their HTTP codes between their Management, Metadata, and Reporting APIs.
This PR is to extend the retry code to handle both a 403 (retryable) error and a 429.
- Gathered information through logging live from users experiencing this error
- Low, it's retry logic and logging.
- revert this branch. bump patch version, and re-release
=> Handle 403 Retryable Errors

tap_google_analytics/client.py
Fixes #24 oversight, where the `errors` key is actually below another `error` key in the response's JSON.
- Unable to reproduce the issue locally, but ran through with an example using this code on the command line directly.
- Low, it's safe error handling code.
- revert this branch, bump patch version, re-release
=> Fix "reason" checking logic for retryable 403s

CHANGELOG.md, setup.py, tap_google_analytics/client.py, tests/test_google_analytics_basic_sync.py
This tap aggressively retries for retryable errors, and it usually makes it through ~3 or 4 requests before getting back on track. This PR makes it less eager to conserve daily quotas.
- None, if the tests pass, it will be enough to cover this.
- Low
- revert this branch and release new patch version
=> Reduce retry frequency

tap_google_analytics/client.py
https://stitchdata.atlassian.net/browse/SUP-2052
Error response was actually this:
```
pp response.json()
{'error': 'invalid_grant', 'error_description': 'Bad Request'}
```
And not how it's documented in the v3 error response example online: https://developers.google.com/analytics/devguides/config/mgmt/v3/errors?hl=en
```
{
"error": {
"errors": [
{
"domain": "global",
"reason": "invalidParameter",
"message": "Invalid value '-1' for max-results. Value must be within the range: [1, 1000]",
"locationType": "parameter",
"location": "max-results"
}
],
"code": 400,
"message": "Invalid value '-1' for max-results. Value must be within the range: [1, 1000]"
}
}
```
- 
=> Grabs error reason from 'reason', 'error_description', or falls back to full json response to ensure a good error message

tap_google_analytics/client.py, tests/unittests/test_client_utilities.py
Add unit testing for retries on 429s and 503s
- 
=> Properly retry on 503 and add unit tests for all status codes that should retry under all conditions

tap_google_analytics/client.py, tests/unittests/test_client_utilities.py
this is a fix in response to this ticket
https://stitchdata.atlassian.net/browse/SUP-2176
we wrote unit test to make sure a `keep-alive` header is on the request, which would ensure that the connection does not snap.
- the unit tests pass
- we ran the tap in discovery and that gets past the `_ensure_access_token` function and successfully writes a catalog
- low
=> added session for request in _ensure_access_token

.circleci/config.yml
Use tap_tester_sandbox env and move build time to early morning to avoid collisions during the day.
- 
=> update build time and use propert tap-tester env

CHANGELOG.md, setup.py, tap_google_analytics/client.py
Reading the file returns the data as a bytes string, rather than a string. This must be decoded as `utf-8`.
The current theory is that testing and local development is using Python 3.8.6, which must have extended the `json` module to be able to handle byte strings as utf-8.
- Low, it's broken still currently
- revert this branch and #56
=> 1.0.5: Decode the json cubes file from bytes as utf8

.circleci/config.yml, setup.py
Fix the setup.
Put ipdb into a dev group alone, put nose and pylint into a test group. Don't pin the ipdb version.
- 
=> don't pin ipdb

CHANGELOG.md, setup.py, tap_google_analytics/discover.py, tests/unittests/test_discovery_utilities.py
Add a string type fallback in case the integer override fields do not receive an integer.
- 
=> Add a string fallback in case we receive non integer values

.circleci/config.yml, tests/test_google_analytics_bookmarks.py
Move build time to avoid conflicts with contractors and internal teams.
6:00am UTC -> 1:00 UTC (8:00pm EST, 6:30am IST)
Move slack notifications to new channel.
https://jira.talendforge.org/browse/TDL-16944
- 
=> move runtime, change slack webhook, skip failing assertions, link ticket

tests/test_google_analytics_bookmarks.py
- Removed unstable assertion which checked that a sync's bookmarked value was equal to today's date for a report using incremental replication.
- This is invalid because google-analytics bookmarks based on the last record which will not always be for today. 
- Also, based on existing expection  [comments](https://github.com/singer-io/tap-google-analytics/pull/58/files#diff-50f9258374526a5b77b9819ef0f9681c3bcbd8f74218f2b7692bf335ea8e3b73L189), added appropriate assertions.
**Note:** This same issue was mentioned in [#58 ](https://github.com/singer-io/tap-google-analytics/pull/58). But it seems like, the expected [assertion](https://github.com/singer-io/tap-google-analytics/pull/58/files#diff-50f9258374526a5b77b9819ef0f9681c3bcbd8f74218f2b7692bf335ea8e3b73L189) was removed instead of an …
=> TDL-16943 Investigate report replication date failures in regression build

tap_google_analytics/discover.py, tap_google_analytics/sync.py
It is possible to get `(other)` as a value from Google for certain fields. This becomes a problem with the date fields because they expect a string formatted as a date/datetime.
This happens because the cardinality of the dimensions selected on the report cause the underlying database to reach its row limit. The data beyond that limit is then put into this `(other)` group.
See this for a more detailed explanation on `(other)` values:
https://support.google.com/analytics/answer/9309767
This PR fixes this by:
- allowing date fields either a date or a string in the schema
- catching errors when parsing datetimes and putting the original value in the record
- Used connection with `(other)` values to ensure proper functionality
- The `sdc_record_hash` is the same for all the `(other)` rows
- …
=> Allow strings in datetime fields that are not dates to be synced

tests/base.py
Attempt to stabilize table selection by not assuming entry 0 is always correct
(write a short description here or paste a link to JIRA)
- 
=> Attempt to stabilize table selection 

.circleci/config.yml
Remove circle regression tests for deprecated tier-1-tap
google-analytics has been officially deprecated as of Dec 12 2024:
https://support.google.com/analytics/answer/11583528?hl=en
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> Remove tier-1-tap tests from deprecated tap
